# SPDX-License-Identifier: Apache-2.0
# Copyright (C) Iurii Trukhin.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../controllers
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cdi-operator
      namespace: cdi
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
