# SPDX-License-Identifier: Apache-2.0
# Copyright (C) Iurii Trukhin.

apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
  annotations:
    cloudring.org/non-claim: downstream-live-import-persistence-backup-and-restore-evidence-required
spec:
  uninstallStrategy: BlockUninstallIfWorkloadsExist
  config:
    featureGates:
      - HonorWaitForFirstConsumer
      - WebhookPvcRendering
  imagePullPolicy: IfNotPresent
  infra:
    nodeSelector:
      kubernetes.io/os: linux
  workload:
    nodeSelector:
      kubernetes.io/os: linux
